sena/sena/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sena/tienda/urls.py
from django.urls import path

from . import views

app_name = "tienda"

urlpatterns = [
    path("", views.index, name="index"),
    path("index2/", views.index2, name="index2"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("catalogo/<str:abrir_off_canva>/", views.catalogo, name="catalogo"),
    path("agendarcita/", views.agendarcita, name="agendarcita"),
    path("inicioAdmin/", views.inicioAdmin, name="inicioAdmin"),
    path("categorias/", views.categorias, name="categorias"),
    path("categorias_buscar/", views.categorias_buscar, name="categorias_buscar"),
    path("categorias_formulario/", views.categorias_formulario, name="categorias_formulario"),
    path("categorias_guardar/", views.categorias_guardar, name="categorias_guardar"),
    path("categorias_editar/<int:id>/", views.categorias_editar, name="categorias_editar"),
    path("categorias_eliminar/<int:id>/", views.categorias_eliminar, name="categorias_eliminar"),
    path("productos/", views.productos, name="productos"),
    path("productos_buscar/", views.productos_buscar, name="productos_buscar"),
    path("productos_formulario/", views.productos_formulario, name="productos_formulario"),
    path("productos_guardar/", views.productos_guardar, name="productos_guardar"),
    path("productos_editar/<int:id>/", views.productos_editar, name="productos_editar"),
    path("productos_eliminar/<int:id>/", views.productos_eliminar, name="productos_eliminar"),
    path("servicios/", views.servicios, name="servicios"),
    path("servicios_buscar/", views.servicios_buscar, name="servicios_buscar"),
    path("servicios_formulario/", views.servicios_formulario, name="servicios_formulario"),
    path("servicios_guardar/", views.servicios_guardar, name="servicios_guardar"),
    path("servicios_editar/<int:id>/", views.servicios_editar, name="servicios_editar"),
    path("servicios_eliminar/<int:id>/", views.servicios_eliminar, name="servicios_eliminar"),
    path("pedidos/", views.pedidos, name="pedidos"),
    path("pedidos_formulario/", views.pedidos_formulario, name="pedidos_formulario"),
    path("pedidos_guardar/", views.pedidos_guardar, name="pedidos_guardar"),
    path("pedidos_editar/<int:id>/", views.pedidos_editar, name="pedidos_editar"),
    path("pedidos_eliminar/<int:id>/", views.pedidos_eliminar, name="pedidos_eliminar"),
    path("usuarios/", views.usuarios, name="usuarios"),
    path("usuarios_buscar/", views.usuarios_buscar, name="usuarios_buscar"),
    path("usuarios_formulario/", views.usuarios_formulario, name="usuarios_formulario"),
    path("usuarios_guardar/", views.usuarios_guardar, name="usuarios_guardar"),
    path("/usuarios_editar/<int:id>/", views.usuarios_editar, name="usuarios_editar"),
    path("usuarios_eliminar/<int:id>/", views.usuarios_eliminar, name="usuarios_eliminar"),
    path("citas/", views.citas, name="citas"),
    path("citas_buscar/", views.citas_buscar, name="citas_buscar"),
    path("citas_formulario/", views.citas_formulario, name="citas_formulario"),
    path("citas_guardar/", views.citas_guardar, name="citas_guardar"),
    path("citas_editar/<int:id>/", views.citas_editar, name="citas_editar"),
    path("citas_eliminar/<int:id>/", views.citas_eliminar, name="citas_eliminar"),
    path("ver_perfil/", views.ver_perfil, name="ver_perfil"),
    path("vacunas/", views.vacunas, name="vacunas"),
    path("estetica/", views.estetica, name="estetica"),
    path("servicios/", views.servicios, name="servicios"),
    path("vacunacion/", views.vacunacion, name="vacunacion"),
    path("historia/", views.historia, name="historia"),
    path("nuestroequipo/", views.nuestroequipo, name="nuestroequipo"),
    path("patrocinios/", views.patrocinios, name="patrocinios"),
    path("contactanos/", views.contactanos, name="contactanos"),

    # Carrito de compras...
    path("carrito_agregar/", views.carrito_agregar, name="carrito_agregar"),
    path("carrito_listar/", views.carrito_listar, name="carrito_listar"),
    path("carrito_eliminar_producto/<int:id>", views.carrito_eliminar_producto, name="carrito_eliminar_producto"),
    path("carrito_actualizar/", views.carrito_actualizar, name="carrito_actualizar"),

    path("establecer_venta/", views.establecer_venta, name="establecer_venta"),
    path("mis_compras/", views.mis_compras, name="mis_compras"),

    path("correo/", views.correo, name="correo"),
    path("pruebas/", views.pruebas, name="pruebas"),
    path("recuperar_contrasena/", views.recuperar_contrasena, name="recuperar_contrasena"),
    path("correo_enviado/", views.correo_enviado, name="correo_enviado"),
    path("nueva_contrasena/", views.nueva_contrasena, name="nueva_contrasena"),
    path("actualizar_contrasenas/", views.actualizar_contrasenas, name="actualizar_contrasenas"),

]

sena/tienda/models.py
from django.db import models


# Create your models here

class Categoria(models.Model):
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=254)
    precio = models.IntegerField()
    fecha_compra = models.DateField()
    stock = models.IntegerField(default=1)
    foto = models.ImageField(null=True, blank=True, upload_to='fotos_productos', default='fotos_productos/default.png')
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, default=1)

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Usuario(models.Model):
    ROLES = (
        (1, 'Administrador'),
        (2, 'Empleado'),
        (3, 'Usuario'),
    )
    foto = models.ImageField(null=True, blank=True, upload_to='fotos', default='fotos/default.png')
    nombre = models.CharField(max_length=254)
    apellido = models.CharField(max_length=254)
    correo = models.EmailField
    nick = models.CharField(max_length=254)
    password = models.CharField(max_length=254)

    rol = models.IntegerField(choices=ROLES, default=3)


    def __str__(self):
        return self.nick


class Pedido(models.Model):
    fecha = models.DateField()
    descripcion = models.TextField(null=True, blank=True)
    precio = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.descripcion


class Cita(models.Model):
    id = models.AutoField(primary_key=True)
    fecha_hora = models.DateTimeField(max_length=254)
    servicio = models.ForeignKey(Servicio, on_delete=models.DO_NOTHING)
    precio = models.IntegerField()
    cliente = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.usuario} - {self.servicio}'

class Venta(models.Model):
    fecha_venta = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    ESTADOS = (
        (1, 'Pendiente'),
        (2, 'Enviado'),
        (3, 'Rechazado'),
    )
    estado = models.IntegerField(choices=ESTADOS, default=1)

    def __str__(self):
        return f'{self.id}'

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    cantidad = models.IntegerField()
    precio_historico = models.IntegerField()

    def __str__(self):
        return f'{self.id} -{self.venta}'

sena/tienda/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from django.core.mail import BadHeaderError, EmailMessage
from django.contrib import messages
from .models import *
from django.db.models import Q
from django.db import IntegrityError, transaction
from django.template import loader
from django.template.loader import render_to_string


# En este archivo, están todas las vistas del software. Con los módulos
# Create your views here.

def index(request):
    if request.session.get("logueo", False):
        return render(request, "tienda/index.html")
    else:
        return HttpResponseRedirect(reverse("tienda:login"))


def catalogo(request, abrir_off_canva=False):
    if abrir_off_canva == "si":
        print("Sí abrir")
    else:
        print("No abrir")
    if request.session.get("logueo", False):
        c = Categoria.objects.all()

        filtro_categoria = request.GET.get("id")

        if filtro_categoria != None and filtro_categoria != '0':
            p = Producto.objects.filter(categoria_id=filtro_categoria)
            request.session["submenu"] = int(filtro_categoria)
        else:
            p = Producto.objects.all()
            request.session["submenu"] = 0

        contexto = {"categorias": c, "productos": p}
        return render(request, "tienda/catalogo/catalogo.html", contexto)
    else:
        return HttpResponseRedirect(reverse("tienda:login"))


def index2(request):
    return render(request, "tienda/index2.html")


def agendarcita(request):
    return render(request, "tienda/citas.html")


def login(request):
    if request.method == "POST":
        usuario = request.POST.get("nick")
        clave = request.POST.get("password")

        try:
            q = Usuario.objects.get(nick=usuario, password=clave)
            messages.success(request, f"Bienvenido sr(a) {q.nombre}!!")
            datos = {
                "rol": q.rol,
                "nombre_rol": q.get_rol_display(),
                "nombre": f"{q.nombre} {q.apellido}",
                "foto": q.foto.url if q.foto else "/media/fotos/default.png",
                "id": q.id
            }
            request.session["logueo"] = datos
            request.session["carrito"] = []
            request.session["cantidad_productos"] = 0
            return HttpResponseRedirect(reverse("tienda:index"))
        except Usuario.DoesNotExist:
            messages.error(request, "Usuario o contraseña no válidos...")
            return render(request, "tienda/iniciarSesion_Registrarse.html")
    else:
        if request.session.get("logueo", False):
            return HttpResponseRedirect(reverse("tienda:index"))
        else:
            return render(request, "tienda/iniciarSesion_Registrarse.html")


def logout(request):
    carrito = request.session.get("carrito", False)
    try:
        del request.session["logueo"]
        if carrito:
            del request.session["carrito"]
            del request.session["cantidad_productos"]
        messages.success(request, "Cesión cerrada correctamente")
    except Exception as e:
        messages.error(request, f"Error: {e}")
    return HttpResponseRedirect(reverse("tienda:login"))


def inicioAdmin(request):
    return render(request, "tienda/inicioAdmin.html")


def recuperar_contrasena(request):
    return render(request, "tienda/usuarios/recuperar_contrasena.html")


def correo_enviado(request):
    destinatario = request.POST.get('correo_recuperar')
    mensaje = """
    <h1 style='color:blue;'>Recuperar contraseña.</h1>
    <p>Este es tu código para recuperar contraseña.</p>
    <a class="btn btn-primary" href="http://127.0.0.1:8000/nueva_contrasena/">Click aquí</a>
    <p>Tienda ADSO, 2024</p>
    """

    try:
        msg = EmailMessage("Tienda ADSO", mensaje, settings.EMAIL_HOST_USER, [destinatario])
        msg.content_subtype = "html"  # Habilitar html
        msg.send()
        return render(request, "tienda/usuarios/correo_enviado.html")
    except BadHeaderError:
        return HttpResponse("Invalid header found.")
    except Exception as e:
        return HttpResponse(f"Error: {e}")


def nueva_contrasena(request):
    return render(request, "tienda/usuarios/nueva_contrasena.html")


def actualizar_contrasenas(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuarioRecuperar')
        contrasena = request.POST.get('contrasenaRecuperar')
        confirmar_contrasena = request.POST.get('confirmarContrasenaRecuperar')

        if contrasena == confirmar_contrasena:
            try:
                # Buscar al usuario por su nombre de usuario
                usuario_obj = Usuario.objects.get(nick=usuario)
                # Actualizar la contraseña del usuario
                usuario_obj.password = contrasena
                usuario_obj.save()
                messages.success(request, "Contraseña actualizada correctamente!!")
                return redirect('tienda:login')  # Redirigir al usuario a la página de inicio de sesión
            except Usuario.DoesNotExist:
                return render(request, "tienda/iniciarSesion_Registrarse.html", {'error': 'El usuario no existe'})
        else:
            return render(request, "tienda/iniciarSesion_Registrarse.html", {'error': 'Las contraseñas no coinciden'})


def categorias(request):
    query = Categoria.objects.all()
    context = {"data": query}
    return render(request, "tienda/categorias/categorias.html", context)


def categorias_buscar(request):
    if request.method == "POST":
        buscar = request.POST.get("buscar")
        query = Categoria.objects.filter(Q(nombre__istartswith=buscar) | Q(descripcion__istartswith=buscar))
        context = {"data": query, "buscado": buscar}
        # select * from Categoria
        return render(request, "tienda/categorias/categorias.html", context)
    return HttpResponseRedirect(reverse("tienda:categorias", args=()))


def categorias_formulario(request):
    return render(request, "tienda/categorias/cat-form.html")


def categorias_guardar(request):
    if request.method == "POST":
        id = request.POST.get("id")
        nombre = request.POST.get("nombre")
        descripcion = request.POST.get("descripcion")

        if id == "":
            # crear
            try:
                pro = Categoria(
                    nombre=nombre,
                    descripcion=descripcion
                )
                pro.save()
                messages.success(request, "Guardado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")
        else:
            # actualizar
            try:
                q = Categoria.objects.get(pk=id)
                q.nombre = nombre
                q.descripcion = descripcion
                q.save()
                messages.success(request, "Actualizado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")

        return HttpResponseRedirect(reverse("tienda:categorias", args=()))

    else:
        messages.warning(request, "No se enviarion datos...")
        return HttpResponseRedirect(reverse("tienda:categorias_formulario", args=()))


def categorias_eliminar(request, id):
    try:
        q = Categoria.objects.get(pk=id)
        q.delete()
        messages.success(request, "Eliminado correctamente!!")
    except Exception as e:
        messages.error(request, f"Error. {e}")
    return HttpResponseRedirect(reverse("tienda:categorias", args=()))


def categorias_editar(request, id):
    q = Categoria.objects.get(pk=id)
    contexto = {"id": id, "data": q}
    return render(request, "tienda/categorias/cat-form.html", contexto)


def productos(request):
    query = Producto.objects.all()
    context = {"data": query}
    return render(request, "tienda/productos/listar.html", context)


def productos_buscar(request):
    if request.method == "POST":
        buscar = request.POST.get("buscar")
        query = Producto.objects.filter(Q(nombre__istartswith=buscar))
        context = {"data": query, "buscado": buscar}
        # select * from Producto
        return render(request, "tienda/productos/listar.html", context)
    return HttpResponseRedirect(reverse("tienda:productos", args=()))


def productos_formulario(request):
    categoria = Categoria.objects.all()

    context = {'categoria': categoria}
    return render(request, "tienda/productos/pro-form.html", context)


def productos_guardar(request):
    if request.method == "POST":
        id = request.POST.get("id")
        nombre = request.POST.get("nombre")
        precio = request.POST.get("precio")
        fecha_compra = request.POST.get("fecha_compra")
        categoria = Categoria.objects.get(pk=request.POST.get("categoria"))

        if id == "":
            # crear
            try:
                pro = Producto(
                    nombre=nombre,
                    precio=precio,
                    fecha_compra=fecha_compra,
                    categoria=categoria
                )
                pro.save()
                messages.success(request, "Guardado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")
        else:
            # actualizar
            try:
                q = Producto.objects.get(pk=id)
                q.nombre = nombre
                q.precio = precio
                q.fecha_compra = fecha_compra
                q.categoria = categoria
                q.save()
                messages.success(request, "Actualizado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")

        return HttpResponseRedirect(reverse("tienda:productos", args=()))

    else:
        messages.warning(request, "No se enviarion datos...")

sena/tienda/templates/tienda/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        +Cotitas - {% block title %} {% endblock %}
    </title>
    <link href="{% static 'tienda/css/styles2.css' %}" rel="stylesheet">
    <link href="{% static 'tienda/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css" />
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'tienda/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'tienda/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'tienda/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'tienda/favicon_io/site.webmanifest' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <style>

        body {
            overflow-x: hidden;
        }

        .botones_usuario {
            margin-top: 10px;
            background-color: #8F82B7 !important;
            border:2px solid transparent !important;
            border-radius: 50px !important;
            font-size: 10px !important;
            margin-left: 10px;
            width: 120px;
            height: 25px;
            text-align: center;
            padding: 4px 10px;
        }

        .menu_usuario {
            border:2px solid black;
            padding: 10px;
            border-radius: 40px 0px 40px 40px;
            margin-top: 70px !important;
        }

        .logo_navbar {
            margin-left: -90px;
        }
    </style>
</head>

<body>

{% if request.session.logueo %}
    <header>
        <nav class="navbar navbar-expand-lg bg-white sticky-top">
            <div class="container">
                <a class="logo_navbar navbar-brand" href="{% url 'tienda:index'  %}"> <img src="{% static 'tienda/img/logo_mascotitas_morado.png' %}" width="150" height="45" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if request.session.logueo.nombre_rol != "Usuario" %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:catalogo' 'no'  %}">Catálogo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:categorias' %}">Categorías</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:citas' %}">Citas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:servicios' %}">Servicios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:pedidos' %}">Pedidos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:productos' %}">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:usuarios' %}">Usuarios</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'tienda:catalogo' 'no'  %}">Catalogo</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <div style="margin-right: -100px">
                    <ul class="navbar-nav me-auto" >
                        <li class="nav-item">
                          <a class="nav-link mr-5 position-relative" type="button" aria-controls="offcanvasRight" style="margin-top: 15px;" onclick="javascript:ver_carrito(`{% url 'tienda:carrito_listar' %}`);">
                              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                        {{ request.session.cantidad_productos|default:0 }}
                                  <span class="visually-hidden">productos</span>
                              </span>
                              <i style="color: black !important; font-size: 30px;" class="bi bi-cart"></i>
                          </a>
                        </li>
                        <li class="nav-item dropdown dropstart" style="">
                            <a id="barra" class="navbar-brand" href="#" role="button"
                               data-bs-toggle="dropdown" style="z-index:1; margin-left: 20px;" width="100px">
                                <img src="{{ request.session.logueo.foto }}" width="70px" height="70px" style="border-radius:100px; ">
                            </a>
                            <ul class="dropdown-menu menu_usuario">
                                <li><h6 style="margin-left: 10px;">{{ request.session.logueo.nombre }} </h6></li>
                                <li><h6 style="font-size: 20px; text-align: center;">{% if request.session.logueo.nombre_rol == "Administrador" %}{{ request.session.logueo.nombre_rol }} {% endif %}</h6></li>
                                {% if request.session.logueo.nombre_rol == "Usuario" %}
                                    <li><a href="{% url 'tienda:mis_compras' %}" class="btn btn-success botones_usuario">Mis compras</a></li>
                                {% endif %}
                                <li><a href="{% url 'tienda:ver_perfil' %}" class="btn btn-success botones_usuario">Ver perfil</a></li>
                                <li><a href="{% url 'tienda:usuarios_editar' request.session.logueo.id %}" class="btn btn-success botones_usuario" >Editar usuario</a></li>
                                <li><a href="{% url 'tienda:logout' %}" class="btn btn-success botones_usuario">Cerrar sesión</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
{% endif %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible"
     role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasRightLabel">Carrito de compras ({{ request.session.cantidad_productos|default:0 }})</h5>
        <span id="loading_cc" class="d-none">
            <div class="spinner-border text-primary" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
        </span>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" id="respuesta_carrito">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <h4>Total: </h4>
    </div>
</div>

{% block contenedor %}
{% endblock %}

<!---------------- Modales ---------------->


<!-- Offcanvas Sidebar -->
<div class="offcanvas offcanvas-start" id="demo">
    <div class="offcanvas-header">
      <h1 class="offcanvas-title">Menú</h1>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
        <div>
            <h5>Productos</h5>
            <ul>
                <li><a class="nav-link" href="alimento.html">Alimento</a></li>
                <li><a class="nav-link" href="delimpieza.html">De limpieza</a></li>
            </ul>
        </div>
        <h5><a class="nav-link" href="servicios.html">Servicios</a></h5>
        <div>
            <h5>Quiénes somos</h5>
            <ul>
                <li><a class="nav-link" href="nuestroequipo.html">Nuestro equipo</a></li>
                <li><a class="nav-link" href="historia.html">Historia</a></li>
                <li><a class="nav-link" href="nuestroequipo.html">Nuestro equipo</a></li>
            </ul>
        </div>
        <h5><a class="nav-link" href="contactanos.html">Contáctanos</a></h5>
    </div>
  </div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'tienda/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <script>
        Fancybox.bind('[data-fancybox="gallery"]', {
            //
        });
    </script>
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <script>
        AOS.init();
      </script>
<script src="{% static 'tienda/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'tienda/js/script.js' %}"></script>

</body>
</html>

sena/tienda/templates/tienda/mensaje.html
{% extends 'tienda/base.html' %}
{% load static %}
{% block title %}Mis ventas{% endblock %}
{% block contenedor %}

{% if data %}
    <h1>Compra exitosa!!!!</h1>

    Productos
    {% for p in data %}
    <h3>Producto: {{ p.producto }}</h3>
    <h3>Cantidad: {{ p.cantidad }}</h3>
    <h3>Precio: {{ p.precio_historico }}</h3>

{% endif %}

{% endblock %}

</body>
</html>