sena/sena/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sena/tienda/urls.py
from django.urls import path

from . import views

app_name = "tienda"

urlpatterns = [
    path("", views.index, name="index"),
    path("index2/", views.index2, name="index2"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("catalogo/<str:abrir_off_canva>/", views.catalogo, name="catalogo"),
    path("agendarcita/", views.agendarcita, name="agendarcita"),
    path("inicioAdmin/", views.inicioAdmin, name="inicioAdmin"),
    path("categorias/", views.categorias, name="categorias"),
    path("categorias_buscar/", views.categorias_buscar, name="categorias_buscar"),
    path("categorias_formulario/", views.categorias_formulario, name="categorias_formulario"),
    path("categorias_guardar/", views.categorias_guardar, name="categorias_guardar"),
    path("categorias_editar/<int:id>/", views.categorias_editar, name="categorias_editar"),
    path("categorias_eliminar/<int:id>/", views.categorias_eliminar, name="categorias_eliminar"),
    path("productos/", views.productos, name="productos"),
    path("productos_buscar/", views.productos_buscar, name="productos_buscar"),
    path("productos_formulario/", views.productos_formulario, name="productos_formulario"),
    path("productos_guardar/", views.productos_guardar, name="productos_guardar"),
    path("productos_editar/<int:id>/", views.productos_editar, name="productos_editar"),
    path("productos_eliminar/<int:id>/", views.productos_eliminar, name="productos_eliminar"),
    path("servicios/", views.servicios, name="servicios"),
    path("servicios_buscar/", views.servicios_buscar, name="servicios_buscar"),
    path("servicios_formulario/", views.servicios_formulario, name="servicios_formulario"),
    path("servicios_guardar/", views.servicios_guardar, name="servicios_guardar"),
    path("servicios_editar/<int:id>/", views.servicios_editar, name="servicios_editar"),
    path("servicios_eliminar/<int:id>/", views.servicios_eliminar, name="servicios_eliminar"),
    path("pedidos/", views.pedidos, name="pedidos"),
    path("pedidos_formulario/", views.pedidos_formulario, name="pedidos_formulario"),
    path("pedidos_guardar/", views.pedidos_guardar, name="pedidos_guardar"),
    path("pedidos_editar/<int:id>/", views.pedidos_editar, name="pedidos_editar"),
    path("pedidos_eliminar/<int:id>/", views.pedidos_eliminar, name="pedidos_eliminar"),
    path("usuarios/", views.usuarios, name="usuarios"),
    path("usuarios_buscar/", views.usuarios_buscar, name="usuarios_buscar"),
    path("usuarios_formulario/", views.usuarios_formulario, name="usuarios_formulario"),
    path("usuarios_guardar/", views.usuarios_guardar, name="usuarios_guardar"),
    path("/usuarios_editar/<int:id>/", views.usuarios_editar, name="usuarios_editar"),
    path("usuarios_eliminar/<int:id>/", views.usuarios_eliminar, name="usuarios_eliminar"),
    path("citas/", views.citas, name="citas"),
    path("citas_buscar/", views.citas_buscar, name="citas_buscar"),
    path("citas_formulario/", views.citas_formulario, name="citas_formulario"),
    path("citas_guardar/", views.citas_guardar, name="citas_guardar"),
    path("citas_editar/<int:id>/", views.citas_editar, name="citas_editar"),
    path("citas_eliminar/<int:id>/", views.citas_eliminar, name="citas_eliminar"),
    path("ver_perfil/", views.ver_perfil, name="ver_perfil"),
    path("vacunas/", views.vacunas, name="vacunas"),
    path("estetica/", views.estetica, name="estetica"),
    path("servicios/", views.servicios, name="servicios"),
    path("vacunacion/", views.vacunacion, name="vacunacion"),
    path("historia/", views.historia, name="historia"),
    path("nuestroequipo/", views.nuestroequipo, name="nuestroequipo"),
    path("patrocinios/", views.patrocinios, name="patrocinios"),
    path("contactanos/", views.contactanos, name="contactanos"),

    # Carrito de compras...
    path("carrito_agregar/", views.carrito_agregar, name="carrito_agregar"),
    path("carrito_listar/", views.carrito_listar, name="carrito_listar"),
    path("carrito_eliminar_producto/<int:id>", views.carrito_eliminar_producto, name="carrito_eliminar_producto"),
    path("carrito_actualizar/", views.carrito_actualizar, name="carrito_actualizar"),

    path("establecer_venta/", views.establecer_venta, name="establecer_venta"),
    path("mis_compras/", views.mis_compras, name="mis_compras"),

    path("correo/", views.correo, name="correo"),
    path("pruebas/", views.pruebas, name="pruebas"),
    path("recuperar_contrasena/", views.recuperar_contrasena, name="recuperar_contrasena"),
    path("correo_enviado/", views.correo_enviado, name="correo_enviado"),
    path("nueva_contrasena/", views.nueva_contrasena, name="nueva_contrasena"),
    path("actualizar_contrasenas/", views.actualizar_contrasenas, name="actualizar_contrasenas"),

]

sena/tienda/models.py
from django.db import models


# Create your models here

class Categoria(models.Model):
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=254)
    precio = models.IntegerField()
    fecha_compra = models.DateField()
    stock = models.IntegerField(default=1)
    foto = models.ImageField(null=True, blank=True, upload_to='fotos_productos', default='fotos_productos/default.png')
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, default=1)

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.nombre


class Usuario(models.Model):
    ROLES = (
        (1, 'Administrador'),
        (2, 'Empleado'),
        (3, 'Usuario'),
    )
    foto = models.ImageField(null=True, blank=True, upload_to='fotos', default='fotos/default.png')
    nombre = models.CharField(max_length=254)
    apellido = models.CharField(max_length=254)
    correo = models.EmailField
    nick = models.CharField(max_length=254)
    password = models.CharField(max_length=254)

    rol = models.IntegerField(choices=ROLES, default=3)


    def __str__(self):
        return self.nick


class Pedido(models.Model):
    fecha = models.DateField()
    descripcion = models.TextField(null=True, blank=True)
    precio = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.descripcion


class Cita(models.Model):
    id = models.AutoField(primary_key=True)
    fecha_hora = models.DateTimeField(max_length=254)
    servicio = models.ForeignKey(Servicio, on_delete=models.DO_NOTHING)
    precio = models.IntegerField()
    cliente = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.usuario} - {self.servicio}'

class Venta(models.Model):
    fecha_venta = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    ESTADOS = (
        (1, 'Pendiente'),
        (2, 'Enviado'),
        (3, 'Rechazado'),
    )
    estado = models.IntegerField(choices=ESTADOS, default=1)

    def __str__(self):
        return f'{self.id}'

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    cantidad = models.IntegerField()
    precio_historico = models.IntegerField()

    def __str__(self):
        return f'{self.id} -{self.venta}'

sena/tienda/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from django.core.mail import BadHeaderError, EmailMessage
from django.contrib import messages
from .models import *
from django.db.models import Q
from django.db import IntegrityError, transaction
from django.template import loader
from django.template.loader import render_to_string


# En este archivo, están todas las vistas del software. Con los módulos
# Create your views here.

def index(request):
    if request.session.get("logueo", False):
        return render(request, "tienda/index.html")
    else:
        return HttpResponseRedirect(reverse("tienda:login"))


def catalogo(request, abrir_off_canva=False):
    if abrir_off_canva == "si":
        print("Sí abrir")
    else:
        print("No abrir")
    if request.session.get("logueo", False):
        c = Categoria.objects.all()

        filtro_categoria = request.GET.get("id")

        if filtro_categoria != None and filtro_categoria != '0':
            p = Producto.objects.filter(categoria_id=filtro_categoria)
            request.session["submenu"] = int(filtro_categoria)
        else:
            p = Producto.objects.all()
            request.session["submenu"] = 0

        contexto = {"categorias": c, "productos": p}
        return render(request, "tienda/catalogo/catalogo.html", contexto)
    else:
        return HttpResponseRedirect(reverse("tienda:login"))


def index2(request):
    return render(request, "tienda/index2.html")


def agendarcita(request):
    return render(request, "tienda/citas.html")


def login(request):
    if request.method == "POST":
        usuario = request.POST.get("nick")
        clave = request.POST.get("password")

        try:
            q = Usuario.objects.get(nick=usuario, password=clave)
            messages.success(request, f"Bienvenido sr(a) {q.nombre}!!")
            datos = {
                "rol": q.rol,
                "nombre_rol": q.get_rol_display(),
                "nombre": f"{q.nombre} {q.apellido}",
                "foto": q.foto.url if q.foto else "/media/fotos/default.png",
                "id": q.id
            }
            request.session["logueo"] = datos
            request.session["carrito"] = []
            request.session["cantidad_productos"] = 0
            return HttpResponseRedirect(reverse("tienda:index"))
        except Usuario.DoesNotExist:
            messages.error(request, "Usuario o contraseña no válidos...")
            return render(request, "tienda/iniciarSesion_Registrarse.html")
    else:
        if request.session.get("logueo", False):
            return HttpResponseRedirect(reverse("tienda:index"))
        else:
            return render(request, "tienda/iniciarSesion_Registrarse.html")


def logout(request):
    carrito = request.session.get("carrito", False)
    try:
        del request.session["logueo"]
        if carrito:
            del request.session["carrito"]
            del request.session["cantidad_productos"]
        messages.success(request, "Cesión cerrada correctamente")
    except Exception as e:
        messages.error(request, f"Error: {e}")
    return HttpResponseRedirect(reverse("tienda:login"))


def inicioAdmin(request):
    return render(request, "tienda/inicioAdmin.html")


def recuperar_contrasena(request):
    return render(request, "tienda/usuarios/recuperar_contrasena.html")


def correo_enviado(request):
    destinatario = request.POST.get('correo_recuperar')
    mensaje = """
    <h1 style='color:blue;'>Recuperar contraseña.</h1>
    <p>Este es tu código para recuperar contraseña.</p>
    <a class="btn btn-primary" href="http://127.0.0.1:8000/nueva_contrasena/">Click aquí</a>
    <p>Tienda ADSO, 2024</p>
    """

    try:
        msg = EmailMessage("Tienda ADSO", mensaje, settings.EMAIL_HOST_USER, [destinatario])
        msg.content_subtype = "html"  # Habilitar html
        msg.send()
        return render(request, "tienda/usuarios/correo_enviado.html")
    except BadHeaderError:
        return HttpResponse("Invalid header found.")
    except Exception as e:
        return HttpResponse(f"Error: {e}")


def nueva_contrasena(request):
    return render(request, "tienda/usuarios/nueva_contrasena.html")


def actualizar_contrasenas(request):
    if request.method == 'POST':
        usuario = request.POST.get('usuarioRecuperar')
        contrasena = request.POST.get('contrasenaRecuperar')
        confirmar_contrasena = request.POST.get('confirmarContrasenaRecuperar')

        if contrasena == confirmar_contrasena:
            try:
                # Buscar al usuario por su nombre de usuario
                usuario_obj = Usuario.objects.get(nick=usuario)
                # Actualizar la contraseña del usuario
                usuario_obj.password = contrasena
                usuario_obj.save()
                messages.success(request, "Contraseña actualizada correctamente!!")
                return redirect('tienda:login')  # Redirigir al usuario a la página de inicio de sesión
            except Usuario.DoesNotExist:
                return render(request, "tienda/iniciarSesion_Registrarse.html", {'error': 'El usuario no existe'})
        else:
            return render(request, "tienda/iniciarSesion_Registrarse.html", {'error': 'Las contraseñas no coinciden'})


def categorias(request):
    query = Categoria.objects.all()
    context = {"data": query}
    return render(request, "tienda/categorias/categorias.html", context)


def categorias_buscar(request):
    if request.method == "POST":
        buscar = request.POST.get("buscar")
        query = Categoria.objects.filter(Q(nombre__istartswith=buscar) | Q(descripcion__istartswith=buscar))
        context = {"data": query, "buscado": buscar}
        # select * from Categoria
        return render(request, "tienda/categorias/categorias.html", context)
    return HttpResponseRedirect(reverse("tienda:categorias", args=()))


def categorias_formulario(request):
    return render(request, "tienda/categorias/cat-form.html")


def categorias_guardar(request):
    if request.method == "POST":
        id = request.POST.get("id")
        nombre = request.POST.get("nombre")
        descripcion = request.POST.get("descripcion")

        if id == "":
            # crear
            try:
                pro = Categoria(
                    nombre=nombre,
                    descripcion=descripcion
                )
                pro.save()
                messages.success(request, "Guardado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")
        else:
            # actualizar
            try:
                q = Categoria.objects.get(pk=id)
                q.nombre = nombre
                q.descripcion = descripcion
                q.save()
                messages.success(request, "Actualizado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")

        return HttpResponseRedirect(reverse("tienda:categorias", args=()))

    else:
        messages.warning(request, "No se enviarion datos...")
        return HttpResponseRedirect(reverse("tienda:categorias_formulario", args=()))


def categorias_eliminar(request, id):
    try:
        q = Categoria.objects.get(pk=id)
        q.delete()
        messages.success(request, "Eliminado correctamente!!")
    except Exception as e:
        messages.error(request, f"Error. {e}")
    return HttpResponseRedirect(reverse("tienda:categorias", args=()))


def categorias_editar(request, id):
    q = Categoria.objects.get(pk=id)
    contexto = {"id": id, "data": q}
    return render(request, "tienda/categorias/cat-form.html", contexto)


def productos(request):
    query = Producto.objects.all()
    context = {"data": query}
    return render(request, "tienda/productos/listar.html", context)


def productos_buscar(request):
    if request.method == "POST":
        buscar = request.POST.get("buscar")
        query = Producto.objects.filter(Q(nombre__istartswith=buscar))
        context = {"data": query, "buscado": buscar}
        # select * from Producto
        return render(request, "tienda/productos/listar.html", context)
    return HttpResponseRedirect(reverse("tienda:productos", args=()))


def productos_formulario(request):
    categoria = Categoria.objects.all()

    context = {'categoria': categoria}
    return render(request, "tienda/productos/pro-form.html", context)


def productos_guardar(request):
    if request.method == "POST":
        id = request.POST.get("id")
        nombre = request.POST.get("nombre")
        precio = request.POST.get("precio")
        fecha_compra = request.POST.get("fecha_compra")
        categoria = Categoria.objects.get(pk=request.POST.get("categoria"))

        if id == "":
            # crear
            try:
                pro = Producto(
                    nombre=nombre,
                    precio=precio,
                    fecha_compra=fecha_compra,
                    categoria=categoria
                )
                pro.save()
                messages.success(request, "Guardado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")
        else:
            # actualizar
            try:
                q = Producto.objects.get(pk=id)
                q.nombre = nombre
                q.precio = precio
                q.fecha_compra = fecha_compra
                q.categoria = categoria
                q.save()
                messages.success(request, "Actualizado correctamente!!")
            except Exception as e:
                messages.error(request, f"Error. {e}")

        return HttpResponseRedirect(reverse("tienda:productos", args=()))

    else:
        messages.warning(request, "No se enviarion datos...")

sena/tienda/templates/tienda/usuarios/mis_compras.html
{% extends 'tienda/base.html' %}
{% load static %}
{% block title %}Mis ventas{% endblock %}
{% block contenedor %}

{% if data %}
    <table class="table table-hover m-3">
        <tr>
            <th>ID</th>
            <th>Fecha de la venta</th>
            <th>Acciones</th>
        </tr>
        {% for venta in data %}
        <tr>
            <td>{{ venta.0.id }}</td>
            <td>{{ venta.0.fecha_venta }}</td>
            <td>
                <button role="button" aria-expanded="false" aria-controls="detalles_{{ venta.0.id }}" type="button" class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#detalles_{{ venta.0.id }}">Detalles</button>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div id="detalles_{{ venta.0.id }}" class="collapse">
                    <table class="table table-hover m-3">
                        <tr>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Precio</th>
                            <th>Subtotal</th>
                        </tr>
                        {% for detalle in venta.0.detalleventa_set.all %}
                        <tr>
                            <td>{{ detalle.producto.nombre }}</td>
                            <td>{{ detalle.cantidad }}</td>
                            <td>{{ detalle.precio_historico }}</td>
                            <td>{{ venta.1 }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </td>
        </tr>
    {% endfor %}
    </table>
        <script>
            function confirmar_eliminar(id, url) {
                if (confirm("¿Estás seguro de que deseas eliminar este pedido?")) {
                    window.location.href = url;
                }
          }
        </script>
    </body>
    </html>
{% endif %}

{% endblock %}

sena/tienda/templates/tienda/usuarios/nueva_contrasena.html
{% extends 'tienda/base2.html' %}
{% load static %}

{% block contenedor %}
<style>
    body {
    background-image: url('{% static 'tienda/img/banner_inicio.jpg' %}') !important;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;
    }

    .contenedor__recuperar_contrasena {
    padding: 20px;
    background-color: white;
    position: absolute;
    border-radius: 20px; text-align: center;
    margin-left: 550px;
    margin-top: 100px;
    }

    .entrar {
    background-color: #8F82B7 !important;
    color: white;
    text-align: center;
    margin-top: 30px;
    }

    .entrar:hover{
    background-color: #FFFFFF;
    color: #8F82B7;
    border: 2px solid #8F82B7;
    transition: all 300ms;
    }

    form {
    display: flex;
    flex-direction: column
    }

    input {
    margin-top: 30px;
    }

    button {
    padding: 10px 40px;
    margin-top: 20px; /* Espacio entre los botones */
    border: none;
    background-color: transparent; /* Fondo transparente */
    color: black; /* Color del texto */
    cursor: pointer;
    outline: none;
}

/* Estilos para el icono de ojo */
.bi {
    display: inline-block; /* Para asegurar que los iconos se muestren correctamente */
    font-size: 1.2rem; /* Tamaño del icono */
    margin-right: 5px; /* Espacio entre el icono y el texto */
}

</style>

<body style="background-image: url('{% static 'tienda/img/banner_inicio.jpg' %}') !important;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;">
    <a href="{% url 'tienda:index' %}">
        <img id="logo" src="{% static 'tienda/img/logo_mascotitas.png' %}" alt="" height="100px" width="100px" >
    </a>

    <div class="contenedor__recuperar_contrasena">
        <form action="{% url 'tienda:actualizar_contrasenas' %}" method="post">
            {% csrf_token %}
            <h2>Recuperar contraseña</h2>
            <input type="text" id="usuarioRecuperar" placeholder="Usuario" required name="usuarioRecuperar">
            <input type="password" id="contrasenaRecuperar" placeholder="Contraseña" required name="contrasenaRecuperar">
            <input type="password" id="confirmarContrasenaRecuperar" placeholder="Confirmar contraseña" required name="confirmarContrasenaRecuperar">
            <button class="entrar" type="submit" class="btn" onclick="validarContrasenaRecuperar()">Actualizar contraseña</button>
        </form>
    </div>

    <!--<script src="../js/script2.js"></script>-->
</body>

</html>
{% endblock %}

sena/tienda/templates/tienda/usuarios/perfil.html
{% extends 'tienda/base.html' %}
{% load static %}
{% block title %} Perfil {% endblock %}
{% block contenedor %}

<div class="card mb-3" style="max-width: 540px; margin-left: 35%;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ request.session.logueo.foto }}" class="img-fluid rounded-start" alt="..." style="width: 200px; height: 200px;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ request.session.logueo.nombre }}</h5>
        <p class="card-text">Rol: {{ request.session.logueo.nombre_rol }} </p>
        <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>


{% endblock %}

sena/tienda/templates/tienda/usuarios/recuperar_contrasena.html
{% extends 'tienda/base2.html' %}
{% load static %}

{% block contenedor %}
<style>
    body {
    background-image: url('{% static 'tienda/img/banner_inicio.jpg' %}') !important;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;
    }

    .contenedor__recuperar_contrasena {
    padding: 20px;
    background-color: white;
    position: absolute;
    border-radius: 20px; text-align: center;
    margin-left: 550px
    }

    .entrar {
    background-color: #8F82B7 !important;
    color: white;
    text-align: center;
    margin-top: 30px;
    }

    .entrar:hover{
    background-color: #FFFFFF;
    color: #8F82B7;
    border: 2px solid #8F82B7;
    transition: all 300ms;
    }

    form {
    display: flex;
    flex-direction: column
    }

    input {
    margin-top: 30px;
    }

</style>

<body>
    <a href="{% url 'tienda:index' %}">
        <img id="logo" src="{% static 'tienda/img/logo_mascotitas.png' %}" alt="" height="100px" width="100px" >
    </a>
    <div class="contenedor__recuperar_contrasena">
        <form action="{% url 'tienda:correo_enviado' %}" method="post">
            {% csrf_token %}
            <h2>Recuperar contraseña</h2>
            <input id="correo_recuperar" type="email" placeholder="Correo" required name="correo_recuperar">
            <button class="entrar btn" type="submit" style="">Entrar</button>
        </form>
    </div>

    <!--<script src="../js/script2.js"></script>-->
</body>

<link href="{% static 'tienda/css/styles2.css' %}" rel="stylesheet">


</html>
{% endblock %}

sena/tienda/templates/tienda/usuarios/usu-form.html
{% extends 'tienda/base.html' %}
{% load static %}
{% block title %} Crear Usuario {% endblock %}
{% block contenedor %}

<style>

    .formulario_contenedor {
        padding: 30px;
        background-color: #8F82B7;
        width: 600px;
        margin-left: 30%;
        border-radius: 50px;
        box-shadow: 0 0 20px gray;
    }

    label {
        color: white
    }

    input, select {
        width: 500px !important;
    }

    .enviar_formulario {
        background-color: #FFFFFF;
        border: 2px solid transparent;
        color: #8F82B7;
    }

    .enviar_formulario:hover {
        background-color: #8F82B7;
        color: #000000;
        border: 2px solid #000000;
    }

</style>

{% if id %}
    <h3>Editar: {{ data.id }}</h3>
{% else %}
    <h3 class="m-3">Crear: </h3>
{% endif %}

<div class="formulario_contenedor">
    <form method="post" action="{% url 'tienda:usuarios_guardar' %}">
    {% csrf_token %}
        <div class="mb-3" hidden>
            <label class="form-label">ID del Usuario:</label>
            <input class="form-control" type="text" name="id" value="{{ data.id }}" readonly>
        </div>
        <div class="mb-3">
            <label class="form-label">Nombre del Usuario:</label>
            <input type="text" class="form-control" placeholder="Nombre" name="nombre" value="{{ data.nombre }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Apellido del Usuario:</label>
            <input type="text" class="form-control" placeholder="Apellido" name="apellido" value="{{ data.apellido }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Nombre de Usuario del Usuario:</label>
            <input type="text" class="form-control" placeholder="Nick" name="nick" value="{{ data.nick }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Contraseña del Usuario:</label>
            <input type="text" class="form-control" placeholder="Password" name="password" value="{{ data.password }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Rol del Usuario:</label>
            <input type="text" class="form-control" placeholder="Rol" name="rol" value="{{ data.rol }}">
        </div>

        {% if id %}
        <button type="submit" class="btn btn-primary enviar_formulario">Actualizar</button>
        {% else %}
        <button type="submit" class="btn btn-primary enviar_formulario">Crear</button>
        {% endif %}
</form>
</div>

{% endblock %}

sena/tienda/templates/tienda/usuarios/usuarios.html
{% extends 'tienda/base.html' %}
{% load static %}
{% block title %}Usuarios{% endblock %}
{% block contenedor %}

<a class="btn btn-success m-3" href="{% url 'tienda:usuarios_formulario' %}" >Crear</a>

{% if data %}

<form class="d-flex" role="search" method="post" action="{% url 'tienda:usuarios_buscar' %}">
    {% csrf_token %}
    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" name="buscar"
           value="{{ buscado }}">
    <a class="btn" href="" type="button"><i class="bi bi-backspace-fill"></i></a>
    <button class="btn btn-success" type="submit">Buscar</button>
</form>

<table class="table table-hover m-3">
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Nickname</th>
        <th>Password</th>
        <th>Rol</th>
        <th>Acciones</th>
    </tr>
    {% for u in data %}
    <tr>
        <td>{{ u.id }}</td>
        <td>{{ u.nombre }}</td>
        <td>{{ u.apellido }}</td>
        <td>{{ u.nick }}</td>
        <td>{{ u.password }}</td>
        <td>{{ u.rol }}</td>
        <td>
            <a href="{% url 'tienda:usuarios_editar' u.id %}" class="btn btn-info">Editar</a>
            <a href="javascript:confirmar_eliminar('{{ u.id }}', '{% url 'tienda:usuarios_eliminar' u.id %}');" class="btn btn-danger">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
</table>

    <script>
        function confirmar_eliminar(id, url) {
            if (confirm("¿Estás seguro de que deseas eliminar este pedido?")) {
                window.location.href = url;
            }
      }
    </script>
</body>
</html>
{% endif %}

{% endblock %}